export const AZULCLARO = "#c3cfd9"
export const LARANJA = "#e8833a"
export const AZULMAISCLARO = "#9EADBA"
export const TEALCLARO = "#1aae9e"
export const TEALESCURO = "#247a6b"
export const CINZAESCURO = "#293845"
export const BRANCO = "#fff"
export const AMARELOCLARO = "#FBE192"
